# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hisab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseGroup',
            new_name='Batch',
        ),
        migrations.RenameModel(
            old_name='ExpenseItem',
            new_name='Item',
        ),
    ]
